In [10]:
import pandas as pd

voltage_df = pd.read_csv(r"D:\Notebook\Bus_Voltage.csv",encoding='cp1125')
voltage_df.drop([2,6,9,12,13,14,15],inplace=True)

active_power_df = pd.read_excel(r"D:\Notebook\active_power_training_data.xlsx")
active_power_df.drop([7],inplace=True)

reactive_power_df = pd.read_excel(r"D:\Notebook\reactive_power_training_data.xlsx")
reactive_power_df.drop([7],inplace=True)

print(voltage_df.shape)
print(active_power_df.shape)
print(reactive_power_df.shape)

(9, 10001)
(9, 10001)
(9, 10001)

In [11]:

import pandas as pd

voltage_df = pd.read_csv(r"D:\Notebook\Bus_Voltage.csv",encoding='cp1125')
active_power_df = pd.read_excel(r"D:\Notebook\active_power_training_data.xlsx")
reactive_power_df = pd.read_excel(r"D:\Notebook\reactive_power_training_data.xlsx")

voltage_df = pd.read_csv(r"D:\Notebook\Bus_Voltage.csv",encoding='cp1125')
voltage_df.drop([2,6,9,12,13,14,15],inplace=True)

active_power_df = pd.read_excel(r"D:\Notebook\active_power_training_data.xlsx")
active_power_df.drop([7],inplace=True)

reactive_power_df = pd.read_excel(r"D:\Notebook\reactive_power_training_data.xlsx")
reactive_power_df.drop([7],inplace=True)



voltage_df = voltage_df.T
active_power_df = active_power_df.T
reactive_power_df = reactive_power_df.T

print(voltage_df.shape)
print(active_power_df.shape)
print(reactive_power_df.shape)

(10001, 9)
(10001, 9)
(10001, 9)

In [39]:
voltage_df

,0,1,2,3,4,5,6,7,8,9,10,11,12
Substation,Anarmani,Damak,Duhabi,Godak,Inaruwa,Kabeli (Amarpur),Katlaya (India),Kusaha,Lahan,Mirchaya,Phidim,Rupani,Siwani HP
training_data_1,1.0,0.995796,1.0,1.0,0.991909,0.99989,0.986612,0.98643,0.992176,1.0,1.0,0.98497,1.0
training_data_2,1.0,0.996506,1.0,1.0,0.992116,0.999932,0.986598,0.986416,0.992084,1.0,1.0,0.984852,1.0
training_data_3,1.0,0.995709,1.0,1.0,0.991702,0.999975,0.986298,0.986116,0.991835,1.0,1.0,0.984602,1.0
training_data_4,1.0,0.996186,1.0,1.0,0.991995,0.999905,0.986578,0.986396,0.992155,1.0,1.0,0.984948,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
training_data_9996,1.0,0.99584,1.0,1.0,0.991782,0.999944,0.986457,0.986274,0.991624,1.0,1.0,0.984408,1.0
training_data_9997,1.0,0.996577,1.0,1.0,0.991865,0.999932,0.986443,0.98626,0.992051,1.0,1.0,0.984835,1.0
training_data_9998,1.0,0.996161,1.0,1.0,0.991773,0.999931,0.986186,0.986003,0.991762,1.0,1.0,0.984535,1.0
training_data_9999,1.0,0.996123,1.0,1.0,0.991682,0.999882,0.98612,0.985938,0.991617,1.0,1.0,0.984393,1.0
training_data_10000,1.0,0.996654,1.0,1.0,0.991606,0.999938,0.985946,0.985764,0.991424,1.0,1.0,0.984205,1.0

In [12]:
result_df = pd.concat([active_power_df, reactive_power_df, voltage_df], axis=1)
print(result_df)
result_df.to_csv("data_for_ML_2.csv")

                            0          1         2          3              4   \
Substation            Anarmani      Damak     Godak    Inaruwa  Kabeli/Amapur
training_data_1      42.416747  21.362095  8.007281  17.149074       2.627481
training_data_2      39.221868   21.61746   7.90037  16.129788       2.734143
training_data_3      41.115663   21.01777   7.85778  16.863076       2.626526
training_data_4      41.547839  20.462775  7.874911    17.1208       2.685381
...                        ...        ...       ...        ...            ...
training_data_9996   39.747643  20.785292  7.830793  16.677609       2.675752
training_data_9997    39.61431  20.709283  7.954822  16.754434        2.59799
training_data_9998   41.170053  21.195998  7.939031  16.883192       2.678688
training_data_9999   41.039329  20.620792  8.033933  16.623465       2.748497
training_data_10000  41.645706  20.413162  7.765196   16.39689       2.604814

                           5          6         8          9          0   ...  \
Substation             Kusaha      Lahan    Phidim     Rupani   Anarmani  ...
training_data_1      9.142593  13.882863  1.808802   14.63449  18.712567  ...
training_data_2      8.847695   13.22775  1.786704  14.442821  16.950968  ...
training_data_3      9.174844  13.275904  1.875011  14.834103  15.549315  ...
training_data_4      9.162229  13.864535  1.765141  15.001393  19.709348  ...
...                       ...        ...       ...        ...        ...  ...
training_data_9996   9.111181  13.732059  1.824785  14.746948  17.429185  ...
training_data_9997   8.994184  13.669015    1.7918  14.273941   20.06771  ...
training_data_9998   8.994465  13.433227  1.835984  14.897661  20.007233  ...
training_data_9999   9.115072  13.528811  1.803861  14.426675  16.837271  ...
training_data_10000   8.80956  13.693368  1.842488  14.896426  21.633322  ...

                           9         0         1      3         4   \
Substation             Rupani  Anarmani     Damak  Godak   Inaruwa
training_data_1      6.426546       1.0  0.995796    1.0  0.991909
training_data_2      6.299856       1.0  0.996506    1.0  0.992116
training_data_3      7.601713       1.0  0.995709    1.0  0.991702
training_data_4      6.548517       1.0  0.996186    1.0  0.991995
...                       ...       ...       ...    ...       ...
training_data_9996   8.032657       1.0   0.99584    1.0  0.991782
training_data_9997   5.986983       1.0  0.996577    1.0  0.991865
training_data_9998   7.820217       1.0  0.996161    1.0  0.991773
training_data_9999   7.716224       1.0  0.996123    1.0  0.991682
training_data_10000  6.717351       1.0  0.996654    1.0  0.991606

                                   5         7         8       10        11
Substation           Kabeli (Amarpur)    Kusaha     Lahan  Phidim    Rupani
training_data_1               0.99989   0.98643  0.992176     1.0   0.98497
training_data_2              0.999932  0.986416  0.992084     1.0  0.984852
training_data_3              0.999975  0.986116  0.991835     1.0  0.984602
training_data_4              0.999905  0.986396  0.992155     1.0  0.984948
...                               ...       ...       ...     ...       ...
training_data_9996           0.999944  0.986274  0.991624     1.0  0.984408
training_data_9997           0.999932   0.98626  0.992051     1.0  0.984835
training_data_9998           0.999931  0.986003  0.991762     1.0  0.984535
training_data_9999           0.999882  0.985938  0.991617     1.0  0.984393
training_data_10000          0.999938  0.985764  0.991424     1.0  0.984205

[10001 rows x 27 columns]